// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: proto/auth/v1/authorization.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteScope int32

const (
	RouteScope_ROUTE_SCOPE_UNSPECIFIED   RouteScope = 0
	RouteScope_ROUTE_SCOPE_PUBLIC        RouteScope = 1
	RouteScope_ROUTE_SCOPE_AUTHENTICATED RouteScope = 2
	RouteScope_ROUTE_SCOPE_AUTHORIZED    RouteScope = 3
)

// Enum value maps for RouteScope.
var (
	RouteScope_name = map[int32]string{
		0: "ROUTE_SCOPE_UNSPECIFIED",
		1: "ROUTE_SCOPE_PUBLIC",
		2: "ROUTE_SCOPE_AUTHENTICATED",
		3: "ROUTE_SCOPE_AUTHORIZED",
	}
	RouteScope_value = map[string]int32{
		"ROUTE_SCOPE_UNSPECIFIED":   0,
		"ROUTE_SCOPE_PUBLIC":        1,
		"ROUTE_SCOPE_AUTHENTICATED": 2,
		"ROUTE_SCOPE_AUTHORIZED":    3,
	}
)

func (x RouteScope) Enum() *RouteScope {
	p := new(RouteScope)
	*p = x
	return p
}

func (x RouteScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_v1_authorization_proto_enumTypes[0].Descriptor()
}

func (RouteScope) Type() protoreflect.EnumType {
	return &file_proto_auth_v1_authorization_proto_enumTypes[0]
}

func (x RouteScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteScope.Descriptor instead.
func (RouteScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{0}
}

type ActionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResource) Reset() {
	*x = ActionResource{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResource) ProtoMessage() {}

func (x *ActionResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResource.ProtoReflect.Descriptor instead.
func (*ActionResource) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResource) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ActionResource) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type Permission struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain           string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Resource         string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Action           string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ImpliedByActions []*ActionResource      `protobuf:"bytes,6,rep,name=implied_by_actions,json=impliedByActions,proto3" json:"implied_by_actions,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"` // optional description for UI
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Permission) GetImpliedByActions() []*ActionResource {
	if x != nil {
		return x.ImpliedByActions
	}
	return nil
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PermissionIds []string               `protobuf:"bytes,3,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"` // optional description for UI
	Scope         map[string]string      `protobuf:"bytes,6,rep,name=scope,proto3" json:"scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *Role) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetScope() map[string]string {
	if x != nil {
		return x.Scope
	}
	return nil
}

type PermissionPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"` // Added domain for modular grouping
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Type          RouteScope             `protobuf:"varint,6,opt,name=type,proto3,enum=auth.v1.RouteScope" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionPath) Reset() {
	*x = PermissionPath{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionPath) ProtoMessage() {}

func (x *PermissionPath) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionPath.ProtoReflect.Descriptor instead.
func (*PermissionPath) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionPath) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionPath) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PermissionPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PermissionPath) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionPath) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionPath) GetType() RouteScope {
	if x != nil {
		return x.Type
	}
	return RouteScope_ROUTE_SCOPE_UNSPECIFIED
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int64                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *PageRequest) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PageRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPage     int64                  `protobuf:"varint,1,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *PageResponse) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type MigratePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Paths         []*PermissionPath      `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigratePermissionsRequest) Reset() {
	*x = MigratePermissionsRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigratePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigratePermissionsRequest) ProtoMessage() {}

func (x *MigratePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigratePermissionsRequest.ProtoReflect.Descriptor instead.
func (*MigratePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{7}
}

func (x *MigratePermissionsRequest) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *MigratePermissionsRequest) GetPaths() []*PermissionPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

type MigratePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigratePermissionsResponse) Reset() {
	*x = MigratePermissionsResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigratePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigratePermissionsResponse) ProtoMessage() {}

func (x *MigratePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigratePermissionsResponse.ProtoReflect.Descriptor instead.
func (*MigratePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{8}
}

type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type HasPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPermissionRequest) Reset() {
	*x = HasPermissionRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionRequest) ProtoMessage() {}

func (x *HasPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionRequest.ProtoReflect.Descriptor instead.
func (*HasPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{11}
}

func (x *HasPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HasPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *HasPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type HasPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPermissionResponse) Reset() {
	*x = HasPermissionResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionResponse) ProtoMessage() {}

func (x *HasPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionResponse.ProtoReflect.Descriptor instead.
func (*HasPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{12}
}

func (x *HasPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type CheckPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Checks        []*ActionResource      `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"` // list of resource+action to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsRequest) Reset() {
	*x = CheckPermissionsRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsRequest) ProtoMessage() {}

func (x *CheckPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{13}
}

func (x *CheckPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionsRequest) GetChecks() []*ActionResource {
	if x != nil {
		return x.Checks
	}
	return nil
}

type CheckPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]bool        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key = "resource:action", value = allowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsResponse) Reset() {
	*x = CheckPermissionsResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsResponse) ProtoMessage() {}

func (x *CheckPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{14}
}

func (x *CheckPermissionsResponse) GetResults() map[string]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListPermissionPathsRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Filter        *ListPermissionPathsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionPathsRequest) Reset() {
	*x = ListPermissionPathsRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionPathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionPathsRequest) ProtoMessage() {}

func (x *ListPermissionPathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionPathsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionPathsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{15}
}

func (x *ListPermissionPathsRequest) GetFilter() *ListPermissionPathsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListPermissionPathsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []*PermissionPath      `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionPathsResponse) Reset() {
	*x = ListPermissionPathsResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionPathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionPathsResponse) ProtoMessage() {}

func (x *ListPermissionPathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionPathsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionPathsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{16}
}

func (x *ListPermissionPathsResponse) GetPaths() []*PermissionPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Pagination    *PageRequest                   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *ListPermissionsRequest_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{17}
}

func (x *ListPermissionsRequest) GetPagination() *PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPermissionsRequest) GetFilter() *ListPermissionsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{18}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PermissionIds []string               `protobuf:"bytes,2,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRoleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PermissionIds []string               `protobuf:"bytes,3,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{22}
}

type AssignRolesToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesToUserRequest) Reset() {
	*x = AssignRolesToUserRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesToUserRequest) ProtoMessage() {}

func (x *AssignRolesToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesToUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRolesToUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{23}
}

func (x *AssignRolesToUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRolesToUserRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type AssignRolesToUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesToUserResponse) Reset() {
	*x = AssignRolesToUserResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesToUserResponse) ProtoMessage() {}

func (x *AssignRolesToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesToUserResponse.ProtoReflect.Descriptor instead.
func (*AssignRolesToUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{24}
}

type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListRoleRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pagination    *PageRequest            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *ListRoleRequest_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{27}
}

func (x *ListRoleRequest) GetPagination() *PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRoleRequest) GetFilter() *ListRoleRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Pagination    *PageResponse          `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResponse) Reset() {
	*x = ListRoleResponse{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResponse) ProtoMessage() {}

func (x *ListRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResponse.ProtoReflect.Descriptor instead.
func (*ListRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{28}
}

func (x *ListRoleResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRoleResponse) GetPagination() *PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPermissionPathsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Domains       []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionPathsRequest_Filter) Reset() {
	*x = ListPermissionPathsRequest_Filter{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionPathsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionPathsRequest_Filter) ProtoMessage() {}

func (x *ListPermissionPathsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionPathsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListPermissionPathsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{15, 0}
}

func (x *ListPermissionPathsRequest_Filter) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListPermissionPathsRequest_Filter) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ListPermissionsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Domains       []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest_Filter) Reset() {
	*x = ListPermissionsRequest_Filter{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest_Filter) ProtoMessage() {}

func (x *ListPermissionsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{17, 0}
}

func (x *ListPermissionsRequest_Filter) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListPermissionsRequest_Filter) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ListRoleRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Scope         map[string]*StringList `protobuf:"bytes,3,rep,name=scope,proto3" json:"scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest_Filter) Reset() {
	*x = ListRoleRequest_Filter{}
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest_Filter) ProtoMessage() {}

func (x *ListRoleRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_authorization_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListRoleRequest_Filter) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_authorization_proto_rawDescGZIP(), []int{27, 0}
}

func (x *ListRoleRequest_Filter) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListRoleRequest_Filter) GetScope() map[string]*StringList {
	if x != nil {
		return x.Scope
	}
	return nil
}

var File_proto_auth_v1_authorization_proto protoreflect.FileDescriptor

const file_proto_auth_v1_authorization_proto_rawDesc = "" +
	"\n" +
	"!proto/auth/v1/authorization.proto\x12\aauth.v1\"D\n" +
	"\x0eActionResource\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xe5\x01\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12E\n" +
	"\x12implied_by_actions\x18\x06 \x03(\v2\x17.auth.v1.ActionResourceR\x10impliedByActions\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\x94\x02\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0epermission_ids\x18\x03 \x03(\tR\rpermissionIds\x125\n" +
	"\vpermissions\x18\x04 \x03(\v2\x13.auth.v1.PermissionR\vpermissions\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12.\n" +
	"\x05scope\x18\x06 \x03(\v2\x18.auth.v1.Role.ScopeEntryR\x05scope\x1a8\n" +
	"\n" +
	"ScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x0ePermissionPath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12'\n" +
	"\x04type\x18\x06 \x01(\x0e2\x13.auth.v1.RouteScopeR\x04type\"K\n" +
	"\vPageRequest\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x03R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"-\n" +
	"\fPageResponse\x12\x1d\n" +
	"\n" +
	"total_page\x18\x01 \x01(\x03R\ttotalPage\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x81\x01\n" +
	"\x19MigratePermissionsRequest\x125\n" +
	"\vpermissions\x18\x01 \x03(\v2\x13.auth.v1.PermissionR\vpermissions\x12-\n" +
	"\x05paths\x18\x02 \x03(\v2\x17.auth.v1.PermissionPathR\x05paths\"\x1c\n" +
	"\x1aMigratePermissionsResponse\"4\n" +
	"\x19GetUserPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x1aGetUserPermissionsResponse\x125\n" +
	"\vpermissions\x18\x01 \x03(\v2\x13.auth.v1.PermissionR\vpermissions\"c\n" +
	"\x14HasPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"1\n" +
	"\x15HasPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"c\n" +
	"\x17CheckPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12/\n" +
	"\x06checks\x18\x02 \x03(\v2\x17.auth.v1.ActionResourceR\x06checks\"\xa0\x01\n" +
	"\x18CheckPermissionsResponse\x12H\n" +
	"\aresults\x18\x01 \x03(\v2..auth.v1.CheckPermissionsResponse.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x1aListPermissionPathsRequest\x12B\n" +
	"\x06filter\x18\x01 \x01(\v2*.auth.v1.ListPermissionPathsRequest.FilterR\x06filter\x1a<\n" +
	"\x06Filter\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\"L\n" +
	"\x1bListPermissionPathsResponse\x12-\n" +
	"\x05paths\x18\x01 \x03(\v2\x17.auth.v1.PermissionPathR\x05paths\"\xcc\x01\n" +
	"\x16ListPermissionsRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.auth.v1.PageRequestR\n" +
	"pagination\x12>\n" +
	"\x06filter\x18\x02 \x01(\v2&.auth.v1.ListPermissionsRequest.FilterR\x06filter\x1a<\n" +
	"\x06Filter\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\"P\n" +
	"\x17ListPermissionsResponse\x125\n" +
	"\vpermissions\x18\x01 \x03(\v2\x13.auth.v1.PermissionR\vpermissions\"p\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\tR\rpermissionIds\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"$\n" +
	"\x12CreateRoleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x01\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0epermission_ids\x18\x03 \x03(\tR\rpermissionIds\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x14\n" +
	"\x12UpdateRoleResponse\"N\n" +
	"\x18AssignRolesToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\"\x1b\n" +
	"\x19AssignRolesToUserResponse\".\n" +
	"\x13GetUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x14GetUserRolesResponse\x12#\n" +
	"\x05roles\x18\x01 \x03(\v2\r.auth.v1.RoleR\x05roles\"\xb6\x02\n" +
	"\x0fListRoleRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.auth.v1.PageRequestR\n" +
	"pagination\x127\n" +
	"\x06filter\x18\x02 \x01(\v2\x1f.auth.v1.ListRoleRequest.FilterR\x06filter\x1a\xb3\x01\n" +
	"\x06Filter\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12@\n" +
	"\x05scope\x18\x03 \x03(\v2*.auth.v1.ListRoleRequest.Filter.ScopeEntryR\x05scope\x1aM\n" +
	"\n" +
	"ScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.auth.v1.StringListR\x05value:\x028\x01\"n\n" +
	"\x10ListRoleResponse\x12#\n" +
	"\x05roles\x18\x01 \x03(\v2\r.auth.v1.RoleR\x05roles\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.auth.v1.PageResponseR\n" +
	"pagination*|\n" +
	"\n" +
	"RouteScope\x12\x1b\n" +
	"\x17ROUTE_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ROUTE_SCOPE_PUBLIC\x10\x01\x12\x1d\n" +
	"\x19ROUTE_SCOPE_AUTHENTICATED\x10\x02\x12\x1a\n" +
	"\x16ROUTE_SCOPE_AUTHORIZED\x10\x032\xad\a\n" +
	"\x14AuthorizationService\x12]\n" +
	"\x12GetUserPermissions\x12\".auth.v1.GetUserPermissionsRequest\x1a#.auth.v1.GetUserPermissionsResponse\x12N\n" +
	"\rHasPermission\x12\x1d.auth.v1.HasPermissionRequest\x1a\x1e.auth.v1.HasPermissionResponse\x12W\n" +
	"\x10CheckPermissions\x12 .auth.v1.CheckPermissionsRequest\x1a!.auth.v1.CheckPermissionsResponse\x12`\n" +
	"\x13ListPermissionPaths\x12#.auth.v1.ListPermissionPathsRequest\x1a$.auth.v1.ListPermissionPathsResponse\x12T\n" +
	"\x0fListPermissions\x12\x1f.auth.v1.ListPermissionsRequest\x1a .auth.v1.ListPermissionsResponse\x12]\n" +
	"\x12MigratePermissions\x12\".auth.v1.MigratePermissionsRequest\x1a#.auth.v1.MigratePermissionsResponse\x12Z\n" +
	"\x11AssignRolesToUser\x12!.auth.v1.AssignRolesToUserRequest\x1a\".auth.v1.AssignRolesToUserResponse\x12K\n" +
	"\fGetUserRoles\x12\x1c.auth.v1.GetUserRolesRequest\x1a\x1d.auth.v1.GetUserRolesResponse\x12E\n" +
	"\n" +
	"CreateRole\x12\x1a.auth.v1.CreateRoleRequest\x1a\x1b.auth.v1.CreateRoleResponse\x12E\n" +
	"\n" +
	"UpdateRole\x12\x1a.auth.v1.UpdateRoleRequest\x1a\x1b.auth.v1.UpdateRoleResponse\x12?\n" +
	"\bListRole\x12\x18.auth.v1.ListRoleRequest\x1a\x19.auth.v1.ListRoleResponseB\vZ\t./v1;authb\x06proto3"

var (
	file_proto_auth_v1_authorization_proto_rawDescOnce sync.Once
	file_proto_auth_v1_authorization_proto_rawDescData []byte
)

func file_proto_auth_v1_authorization_proto_rawDescGZIP() []byte {
	file_proto_auth_v1_authorization_proto_rawDescOnce.Do(func() {
		file_proto_auth_v1_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_v1_authorization_proto_rawDesc), len(file_proto_auth_v1_authorization_proto_rawDesc)))
	})
	return file_proto_auth_v1_authorization_proto_rawDescData
}

var file_proto_auth_v1_authorization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_auth_v1_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_auth_v1_authorization_proto_goTypes = []any{
	(RouteScope)(0),                           // 0: auth.v1.RouteScope
	(*ActionResource)(nil),                    // 1: auth.v1.ActionResource
	(*Permission)(nil),                        // 2: auth.v1.Permission
	(*Role)(nil),                              // 3: auth.v1.Role
	(*PermissionPath)(nil),                    // 4: auth.v1.PermissionPath
	(*PageRequest)(nil),                       // 5: auth.v1.PageRequest
	(*PageResponse)(nil),                      // 6: auth.v1.PageResponse
	(*StringList)(nil),                        // 7: auth.v1.StringList
	(*MigratePermissionsRequest)(nil),         // 8: auth.v1.MigratePermissionsRequest
	(*MigratePermissionsResponse)(nil),        // 9: auth.v1.MigratePermissionsResponse
	(*GetUserPermissionsRequest)(nil),         // 10: auth.v1.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil),        // 11: auth.v1.GetUserPermissionsResponse
	(*HasPermissionRequest)(nil),              // 12: auth.v1.HasPermissionRequest
	(*HasPermissionResponse)(nil),             // 13: auth.v1.HasPermissionResponse
	(*CheckPermissionsRequest)(nil),           // 14: auth.v1.CheckPermissionsRequest
	(*CheckPermissionsResponse)(nil),          // 15: auth.v1.CheckPermissionsResponse
	(*ListPermissionPathsRequest)(nil),        // 16: auth.v1.ListPermissionPathsRequest
	(*ListPermissionPathsResponse)(nil),       // 17: auth.v1.ListPermissionPathsResponse
	(*ListPermissionsRequest)(nil),            // 18: auth.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),           // 19: auth.v1.ListPermissionsResponse
	(*CreateRoleRequest)(nil),                 // 20: auth.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),                // 21: auth.v1.CreateRoleResponse
	(*UpdateRoleRequest)(nil),                 // 22: auth.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),                // 23: auth.v1.UpdateRoleResponse
	(*AssignRolesToUserRequest)(nil),          // 24: auth.v1.AssignRolesToUserRequest
	(*AssignRolesToUserResponse)(nil),         // 25: auth.v1.AssignRolesToUserResponse
	(*GetUserRolesRequest)(nil),               // 26: auth.v1.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),              // 27: auth.v1.GetUserRolesResponse
	(*ListRoleRequest)(nil),                   // 28: auth.v1.ListRoleRequest
	(*ListRoleResponse)(nil),                  // 29: auth.v1.ListRoleResponse
	nil,                                       // 30: auth.v1.Role.ScopeEntry
	nil,                                       // 31: auth.v1.CheckPermissionsResponse.ResultsEntry
	(*ListPermissionPathsRequest_Filter)(nil), // 32: auth.v1.ListPermissionPathsRequest.Filter
	(*ListPermissionsRequest_Filter)(nil),     // 33: auth.v1.ListPermissionsRequest.Filter
	(*ListRoleRequest_Filter)(nil),            // 34: auth.v1.ListRoleRequest.Filter
	nil,                                       // 35: auth.v1.ListRoleRequest.Filter.ScopeEntry
}
var file_proto_auth_v1_authorization_proto_depIdxs = []int32{
	1,  // 0: auth.v1.Permission.implied_by_actions:type_name -> auth.v1.ActionResource
	2,  // 1: auth.v1.Role.permissions:type_name -> auth.v1.Permission
	30, // 2: auth.v1.Role.scope:type_name -> auth.v1.Role.ScopeEntry
	0,  // 3: auth.v1.PermissionPath.type:type_name -> auth.v1.RouteScope
	2,  // 4: auth.v1.MigratePermissionsRequest.permissions:type_name -> auth.v1.Permission
	4,  // 5: auth.v1.MigratePermissionsRequest.paths:type_name -> auth.v1.PermissionPath
	2,  // 6: auth.v1.GetUserPermissionsResponse.permissions:type_name -> auth.v1.Permission
	1,  // 7: auth.v1.CheckPermissionsRequest.checks:type_name -> auth.v1.ActionResource
	31, // 8: auth.v1.CheckPermissionsResponse.results:type_name -> auth.v1.CheckPermissionsResponse.ResultsEntry
	32, // 9: auth.v1.ListPermissionPathsRequest.filter:type_name -> auth.v1.ListPermissionPathsRequest.Filter
	4,  // 10: auth.v1.ListPermissionPathsResponse.paths:type_name -> auth.v1.PermissionPath
	5,  // 11: auth.v1.ListPermissionsRequest.pagination:type_name -> auth.v1.PageRequest
	33, // 12: auth.v1.ListPermissionsRequest.filter:type_name -> auth.v1.ListPermissionsRequest.Filter
	2,  // 13: auth.v1.ListPermissionsResponse.permissions:type_name -> auth.v1.Permission
	3,  // 14: auth.v1.GetUserRolesResponse.roles:type_name -> auth.v1.Role
	5,  // 15: auth.v1.ListRoleRequest.pagination:type_name -> auth.v1.PageRequest
	34, // 16: auth.v1.ListRoleRequest.filter:type_name -> auth.v1.ListRoleRequest.Filter
	3,  // 17: auth.v1.ListRoleResponse.roles:type_name -> auth.v1.Role
	6,  // 18: auth.v1.ListRoleResponse.pagination:type_name -> auth.v1.PageResponse
	35, // 19: auth.v1.ListRoleRequest.Filter.scope:type_name -> auth.v1.ListRoleRequest.Filter.ScopeEntry
	7,  // 20: auth.v1.ListRoleRequest.Filter.ScopeEntry.value:type_name -> auth.v1.StringList
	10, // 21: auth.v1.AuthorizationService.GetUserPermissions:input_type -> auth.v1.GetUserPermissionsRequest
	12, // 22: auth.v1.AuthorizationService.HasPermission:input_type -> auth.v1.HasPermissionRequest
	14, // 23: auth.v1.AuthorizationService.CheckPermissions:input_type -> auth.v1.CheckPermissionsRequest
	16, // 24: auth.v1.AuthorizationService.ListPermissionPaths:input_type -> auth.v1.ListPermissionPathsRequest
	18, // 25: auth.v1.AuthorizationService.ListPermissions:input_type -> auth.v1.ListPermissionsRequest
	8,  // 26: auth.v1.AuthorizationService.MigratePermissions:input_type -> auth.v1.MigratePermissionsRequest
	24, // 27: auth.v1.AuthorizationService.AssignRolesToUser:input_type -> auth.v1.AssignRolesToUserRequest
	26, // 28: auth.v1.AuthorizationService.GetUserRoles:input_type -> auth.v1.GetUserRolesRequest
	20, // 29: auth.v1.AuthorizationService.CreateRole:input_type -> auth.v1.CreateRoleRequest
	22, // 30: auth.v1.AuthorizationService.UpdateRole:input_type -> auth.v1.UpdateRoleRequest
	28, // 31: auth.v1.AuthorizationService.ListRole:input_type -> auth.v1.ListRoleRequest
	11, // 32: auth.v1.AuthorizationService.GetUserPermissions:output_type -> auth.v1.GetUserPermissionsResponse
	13, // 33: auth.v1.AuthorizationService.HasPermission:output_type -> auth.v1.HasPermissionResponse
	15, // 34: auth.v1.AuthorizationService.CheckPermissions:output_type -> auth.v1.CheckPermissionsResponse
	17, // 35: auth.v1.AuthorizationService.ListPermissionPaths:output_type -> auth.v1.ListPermissionPathsResponse
	19, // 36: auth.v1.AuthorizationService.ListPermissions:output_type -> auth.v1.ListPermissionsResponse
	9,  // 37: auth.v1.AuthorizationService.MigratePermissions:output_type -> auth.v1.MigratePermissionsResponse
	25, // 38: auth.v1.AuthorizationService.AssignRolesToUser:output_type -> auth.v1.AssignRolesToUserResponse
	27, // 39: auth.v1.AuthorizationService.GetUserRoles:output_type -> auth.v1.GetUserRolesResponse
	21, // 40: auth.v1.AuthorizationService.CreateRole:output_type -> auth.v1.CreateRoleResponse
	23, // 41: auth.v1.AuthorizationService.UpdateRole:output_type -> auth.v1.UpdateRoleResponse
	29, // 42: auth.v1.AuthorizationService.ListRole:output_type -> auth.v1.ListRoleResponse
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_auth_v1_authorization_proto_init() }
func file_proto_auth_v1_authorization_proto_init() {
	if File_proto_auth_v1_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_v1_authorization_proto_rawDesc), len(file_proto_auth_v1_authorization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_v1_authorization_proto_goTypes,
		DependencyIndexes: file_proto_auth_v1_authorization_proto_depIdxs,
		EnumInfos:         file_proto_auth_v1_authorization_proto_enumTypes,
		MessageInfos:      file_proto_auth_v1_authorization_proto_msgTypes,
	}.Build()
	File_proto_auth_v1_authorization_proto = out.File
	file_proto_auth_v1_authorization_proto_goTypes = nil
	file_proto_auth_v1_authorization_proto_depIdxs = nil
}
